sudo: required

language: java
jdk: oraclejdk8

services:
  - docker

before_script:
 - echo "Starting build"
script:
 - mvn clean package
after_script:
 - echo "Script finished"
after_success:
 - echo "Build was successful. $TRAVIS_TEST_RESULT"
 - bash <(curl -s https://codecov.io/bash)
after_failure:
 - echo "Build was failed"